### ISSUE TITLE
example error

### ISSUE THREAD

**Issue by BruceLee66** [jackee777/babelnetpy#4]
Sorry,i did not found any file called "key.txt".Could you please update or give some instructions about how to use.

**Comment by jackee777** [comment]
Hello, BruceLee66.
The "key.txt" in the example code means that you need to make "key.txt" and write your API key in that file. The API key is written on the home page after log-in.

As the other use, we write only `BabelNet("your API key")` directly, and we don't need to make the additional file.
(The reason that I used the "key.txt" in the example is to avoid a mistake that anyone uploads own API code.)
